# Generated by Django 3.2.24 on 2024-06-22 05:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='job_model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.CharField(max_length=200)),
                ('job_location', models.CharField(max_length=100)),
                ('job_description', models.TextField()),
                ('job_posted_date', models.DateTimeField(auto_now_add=True)),
                ('apply_url', models.URLField()),
                ('posted_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs_posted', to='user.profile')),
            ],
        ),
    ]
